#!/bin/sh
# usage: evalzsh [version] < script
# USE_DOCKER=true evalzsh [version] < script
# env USE_DOCKER=true evalzsh [version] < script # for non-bourne shells

# requires:
# * podman (or docker really)
# * pulling all the desired tags first
# podman pull --all-tags zshusers/zsh

# testing a script against every supported zsh version
# podman images --filter='reference=zshusers/zsh' --format='{{ .Tag }}' |
# while read -r tag; do
#   echo "zsh version: $tag"
#   evalzsh "$tag" < script
# done

# don't nice background jobs
[ -n "$ZSH_VERSION" ] && setopt nobgnice

tag=${1:-latest}

runtime() {
  if [ -n "$USE_DOCKER" ]; then
    docker "$@"
  else
    podman "$@"
  fi
}

manager() {
  runtime run --rm -i "--net=${NETWORK:-none}" "--pull=${PULL:-never}" \
    "--workdir=${WORKDIR:-/root}" \
    "--label=evalzsh=$$" \
    "zshusers/zsh:$tag" \
    zsh -li --extendedglob --multibyte -c 'source /dev/stdin'
}

# feeding input to the container
{ cat; printf '%s\n' 'echo "exitstatus: $?"'; } |

if [ -z "$TIMEOUT" ]; then
  manager
else
  case "$TIMEOUT" in
    # don't allow the command to run for more than 8 seconds from now
    *[!0123456789]*) TIMEOUT=8;;
  esac
  manager &
  pid=$!
  (
    sleep "$TIMEOUT"
    runtime kill "$(runtime ps -f "label=evalzsh=$$" -q)" >/dev/null 2>&1
    echo "$TIMEOUT" second timeout reached
  ) &
  cleanup=$!
  trap 'kill "$cleanup" >/dev/null 2>&1' EXIT
  wait "$pid"
fi
